 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chatapp-ingress
  annotations:
   nginx.ingress.kubernetes.io/rewrite-target: /
   kubernetes.io/ingress.class: "nginx"    
spec:
  rules:
  - host: chatapp.devmani.ml  # Replace with the URL you want.
    http:
      paths:
      - path: /
        backend:
          serviceName: chatapp
          servicePort: 80
