apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller-svc
  annotations:
    external-dns.alpha.kubernetes.io/hostname: devmani.ml
spec:
  externalTrafficPolicy: "Local"
  type: LoadBalancer
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: nginx-ingress
